export const QUIZZES = 'QUIZZES'
export const DECKS = 'DECKS'


export const LOAD_QUIZ = 'LOAD_QUIZ'
export const LOAD_DECK = 'LOAD_DECK'

export const ADD_QUIZ = 'ADD_QUIZ'
export const ADD_DECK = 'ADD_DECK'
export const ADD_QUIZ_DECK = 'ADD_QUIZ_DECK'

export const GET_DECK_QUESTIONS = 'GET_DECK_QUESTIONS'
export const ADD_QUIZ_ANSWER = 'ADD_QUIZ_ANSWER'
export const CLEAR_QUIZ_ANSWER = 'CLEAR_QUIZ_ANSWER'
export const SET_AVAILABLE_QUIZ = 'SET_AVAILABLE_QUIZ'
export const REMOVE_AVAILABLE_QUIZ = 'REMOVE_AVAILABLE_QUIZ'

export const NOTIFICATION_KEY = 'UDACITY_FLASHCARD_NOTIFICATION'